"""End-to-end dry run of the Phase 6 agent-facing judge tool.

Unlike ``app/demo.py`` (which exercises the eval *arms*), this drives the
real MCP server over stdio exactly as an MCP client would: it spawns
``app.mcp_judge_server``, lists its tools, then calls
``score_financial_sentiment`` on a stratified handful of real Financial
PhraseBank sentences plus a few inputs that should be rejected.

Nothing is written to Postgres -- this is a disposable check that the whole
path (MCP transport -> arms.yaml judge config -> judge model -> rubric
parse) works before you rely on it.

Run from inside backend/:

    # candidate answers generated by a configured eval arm
    uv run python -m scripts.judge_tool_dryrun --arm qwen3-8b-local --n 6

    # or fabricate the candidate answers (no eval model needed, judge only)
    uv run python -m scripts.judge_tool_dryrun --synthetic --n 6

Exit code is non-zero if the tool is missing, a valid call errors, or a
call that should have been rejected succeeds.
"""
import argparse
import asyncio
import random
import sys
import tempfile
from pathlib import Path

from dotenv import load_dotenv
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

from app.config.arms import load_arms
from app.data.financial_phrasebank import PhrasebankExample, load_examples

DATA_PATH = (
    Path(__file__).resolve().parent.parent
    / "data"
    / "financial_phrasebank"
    / "sentences_allagree.txt"
)
ARMS_PATH = Path(__file__).resolve().parent.parent / "arms.yaml"
TOOL_NAME = "score_financial_sentiment"
LABELS = ("positive", "negative", "neutral")

# Inputs the tool must reject before making a judge call.
NEGATIVE_CASES = [
    {
        "label": "blank input_text",
        "args": {"input_text": "   ", "gold_label": "positive", "model_output": "Positive."},
    },
    {
        "label": "blank model_output",
        "args": {"input_text": "Profits rose.", "gold_label": "positive", "model_output": ""},
    },
    {
        "label": "out-of-domain gold_label",
        "args": {"input_text": "Profits rose.", "gold_label": "bullish", "model_output": "Up."},
    },
]


def sample_by_label(
    examples: list[PhrasebankExample], n: int, seed: int | None = None
) -> list[PhrasebankExample]:
    """A roughly even sample across positive/negative/neutral, deterministic
    for a given seed."""
    if n >= len(examples):
        return list(examples)

    rng = random.Random(seed)
    by_label: dict[str, list[PhrasebankExample]] = {label: [] for label in LABELS}
    for example in examples:
        by_label.setdefault(example.label, []).append(example)
    for bucket in by_label.values():
        rng.shuffle(bucket)

    picked: list[PhrasebankExample] = []
    quota = max(1, n // len(LABELS))
    for label in LABELS:
        picked.extend(by_label[label][:quota])

    if len(picked) < n:
        leftover = [e for label in LABELS for e in by_label[label][quota:]]
        rng.shuffle(leftover)
        picked.extend(leftover[: n - len(picked)])

    return picked[:n]


def classify_prompt(sentence: str) -> str:
    return (
        "Classify the financial sentiment of the following sentence as "
        "positive, negative, or neutral, then explain in one sentence.\n\n"
        f"Sentence: {sentence}"
    )


def synthetic_output(example: PhrasebankExample, wrong: bool) -> str:
    label = example.label
    if wrong:
        label = {"positive": "negative", "negative": "positive", "neutral": "positive"}[label]
    return f"This reads as {label} sentiment."


def format_row(sentence: str, gold: str, candidate: str, result: dict) -> str:
    head = f"  gold={gold:<8} | {sentence[:70]}"
    body = f"    candidate: {candidate[:80]}"
    if "error" in result:
        return f"{head}\n{body}\n    -> ERROR: {result['error']}\n"
    return (
        f"{head}\n{body}\n"
        f"    -> score={result['score']} ({result['judge_model']}): {result['rationale']}\n"
    )


async def _run(arm_name: str | None, synthetic: bool, n: int, seed: int) -> int:
    examples = sample_by_label(load_examples(DATA_PATH), n=n, seed=seed)

    generate = None
    if not synthetic:
        arms = load_arms(str(ARMS_PATH))
        if arm_name not in arms:
            print(f"arm {arm_name!r} not in arms.yaml (have: {', '.join(arms)})")
            return 1
        generate = arms[arm_name].generate

    params = StdioServerParameters(
        command="uv", args=["run", "python", "-m", "app.mcp_judge_server"]
    )
    failures = 0

    # The server logs a full traceback to stderr for every rejected call
    # (including the expected NEGATIVE_CASES). Capture it and only surface it
    # if the run actually fails.
    server_log = tempfile.NamedTemporaryFile(mode="w+", suffix=".log", prefix="judge-dryrun-")
    async with stdio_client(params, errlog=server_log) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            listed = {t.name for t in (await session.list_tools()).tools}
            print(f"tools advertised: {sorted(listed)}")
            if TOOL_NAME not in listed:
                print(f"FAIL: {TOOL_NAME!r} not advertised by the server")
                return 1

            print(f"\nscoring {len(examples)} real Financial PhraseBank sentences\n")
            scores: list[int] = []
            judge_models: set[str] = set()
            for i, example in enumerate(examples):
                if synthetic:
                    candidate = synthetic_output(example, wrong=(i % 4 == 0))
                else:
                    try:
                        candidate = generate(classify_prompt(example.text)).text.strip()
                    except Exception as exc:  # noqa: BLE001 - report and move on
                        print(f"  arm generate failed for {example.text[:50]!r}: {exc}")
                        failures += 1
                        continue

                result = await session.call_tool(
                    TOOL_NAME,
                    {
                        "input_text": example.text,
                        "gold_label": example.label,
                        "model_output": candidate,
                    },
                )
                if result.is_error:
                    msg = result.content[0].text if result.content else "unknown error"
                    print(format_row(example.text, example.label, candidate, {"error": msg}))
                    failures += 1
                    continue

                payload = result.structured_content
                print(format_row(example.text, example.label, candidate, payload))
                scores.append(payload["score"])
                judge_models.add(payload["judge_model"])

            print("checking input validation\n")
            for case in NEGATIVE_CASES:
                result = await session.call_tool(TOOL_NAME, case["args"])
                ok = result.is_error
                print(f"  {case['label']:<24} -> {'rejected (ok)' if ok else 'ACCEPTED (FAIL)'}")
                if not ok:
                    failures += 1

            print("\n--- summary ---")
            if scores:
                dist = {s: scores.count(s) for s in sorted(set(scores))}
                print(f"scored: {len(scores)}  mean: {sum(scores) / len(scores):.2f}  distribution: {dist}")
                print(f"judge model(s): {', '.join(sorted(judge_models))}")
            print(f"failures: {failures}")

    if failures:
        server_log.seek(0)
        captured = server_log.read().strip()
        if captured:
            print("\n--- captured server stderr ---")
            print(captured)
    server_log.close()

    return 1 if failures else 0


def main() -> None:
    load_dotenv()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arm", default="qwen3-8b-local", help="eval arm that generates candidate answers")
    parser.add_argument("--synthetic", action="store_true", help="fabricate candidate answers instead of calling an arm")
    parser.add_argument("--n", type=int, default=6, help="number of real sentences to score")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    code = asyncio.run(_run(args.arm, args.synthetic, args.n, args.seed))
    sys.exit(code)


if __name__ == "__main__":
    main()
